return {
  {
    "catppuccin/nvim",
    lazy = false,
    enabled = true,
    priority = 1000,
    name = "catppuccin",
    opts = {
      flavour = "macchiato",
      background = {
        dark = "macchiato",
        light = "latte",
      },
      transparent_background = true,
      term_colors = true,
      integrations = {
        aerial = true,
        alpha = true,
        cmp = true,
        dap = true,
        dap_ui = true,
        dashboard = true,
        flash = true,
        gitsigns = true,
        grug_far = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = false, scope_color = "lavender" },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          inlay_hints = {
            background = true,
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
        blink_cmp = true,
      },
      highlight_overrides = {
        macchiato = function(macchiato)
          return {
            ["@variable.member"] = { fg = macchiato.blue },
            ["@variable"] = { fg = macchiato.yellow },
            ["@constructor.typescript"] = { fg = macchiato.peach },
            ["@type"] = { fg = macchiato.yellow },
            ["@type.builtin"] = { fg = macchiato.peach },
            ["@tag"] = { fg = macchiato.blue },
            ["@tag.builtin.tsx"] = { fg = macchiato.blue },
            ["@lsp.type.property"] = { fg = macchiato.blue },
            ["@tag.delimiter"] = { fg = macchiato.blue },
            ["@tag.attribute.tsx"] = { fg = macchiato.yellow, style = {} },
            ["@lsp.type.interface.typescript"] = { fg = macchiato.yellow },
            ["@lsp.type.interface.typescriptreact"] = { fg = macchiato.peach },
            ["@string.special.url.tsx"] = { fg = macchiato.green, style = { "underline" } },
            ["@attribute.typescript"] = { fg = macchiato.maroon },
            ["@function"] = { fg = macchiato.maroon },
            ["@lsp.function.typescript"] = { link = "@function" },
            ["@lsp.type.parameter.typescriptreact"] = { link = "@constant" },
            ["@module"] = { fg = macchiato.maroon, style = {} },
            ["@property.yaml"] = { fg = macchiato.blue },
            ["@punctuation.bracket"] = { fg = macchiato.lavender },
            ["@property.styled"] = { link = "@lsp.type.property" },
            ["@property.class.styled"] = { link = "@variable" },
            ["@spell.tsx"] = { fg = macchiato.lavender },
            -- ["MiniIndentscopeSymbol"] = { fg = macchiato.overlay1 },
            ["DiagnosticUnnecessary"] = { fg = macchiato.blue },
            ["@constant.bash"] = { fg = macchiato.blue },
            ["@property.json"] = { fg = macchiato.blue },
            ["@property.jsonc"] = { fg = macchiato.blue },
            ["CursorLine"] = { bg = macchiato.base },
            ["Visual"] = { bg = macchiato.surface2, style = {} },
            ["LspReferenceWrite"] = { bg = macchiato.surface0 },
            ["LspReferenceText"] = { bg = macchiato.surface0 },
            ["@lsp.type.parameter.typescript"] = { fg = macchiato.peach },
            ["Cursor"] = { bg = macchiato.flamingo },
            ["BlinkCmpMenuSelection"] = { bg = macchiato.mauve, fg = macchiato.surface0, blend = 10 },
            ["BlinkCmpMenu"] = { bg = macchiato.surface0, blend = 5 },
            ["BlinkCmpMenuBorder"] = { fg = macchiato.flamingo, bg = macchiato.surface0, blend = 10 },
            ["NeominimapCursorLine"] = { bg = macchiato.base, blend = 2 },
            ["BlinkCmpScrollBarThumb"] = {
              bg = macchiato.pink,
              blend = 10,
            },
            ["BlinkCmpSignatureHelp"] = { bg = macchiato.surface0, blend = 5 },
            ["BlinkCmpSignatureHelpBorder"] = { fg = macchiato.flamingo, bg = macchiato.surface0, blend = 10 },
            ["BlinkCmpDoc"] = { bg = macchiato.surface0, blend = 5 },
            ["BlinkCmpDocBorder"] = { fg = macchiato.flamingo, bg = macchiato.surface0, blend = 10 },

            ["SnackIndentBlue"] = { fg = macchiato.blue },
            ["BlinkIndentLavender"] = { fg = macchiato.lavender },
            ["BlinkIndentSapphire"] = { fg = macchiato.sapphire },
            ["BlinkIndentSky"] = { fg = macchiato.sky },
            ["BlinkIndentGreen"] = { fg = macchiato.green },
            ["BlinkIndentTeal"] = { fg = macchiato.teal },
            ["BlinkIndentYellow"] = { fg = macchiato.yellow },
            ["BlinkIndentPeach"] = { fg = macchiato.peach },
            ["BlinkIndentMaroon"] = { fg = macchiato.maroon },
            ["BlinkIndentRed"] = { fg = macchiato.red },
            ["BlinkIndentPink"] = { fg = macchiato.pink },
            ["BlinkIndentMauve"] = { fg = macchiato.mauve },
            ["BlinkIndentFlamingo"] = { fg = macchiato.flamingo },
            ["SnacksIndent"] = { fg = macchiato.surface1 },
          }
        end,
      },
    },
  },
}
